CONFIG_GPIO=y
CONFIG_PWM=y
CONFIG_COUNTER=y
CONFIG_SERIAL=y

CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_PROCESS_THREAD_STACK_SIZE=2048

CONFIG_SENSOR=y
CONFIG_SENSOR_QUAD_ENCODER=y

CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_UART_LINE_CRTL=y

CONFIG_PID=y

CONFIG_THREAD_MONITOR=y
CONFIG_MAIN_STACK_SIZE=4096

CONFIG_TIMER=y

CONFIG_RTT_CONSOLE=y
CONFIG_USE_SEGGER_RTT=y

CONFIG_CLOCK_CONTROL=y
CONFIG_PINCTRL=y